apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniauth-api
spec:
  selector:
    matchLabels:
      app: uniauth-api
  template:
    metadata:
      labels:
        app: uniauth-api
    spec:
      containers:
        - name: uniauth-container
          image: strbagus/uniauth:2.0.2
          env:
            - name: APP_DOMAIN
              value: strbagus.my.id
            - name: SERVER_PORT
              value: "8051"
            - name: BASE_URL
              value: /
            - name: JWKS_KID
              value: xBm249Cm6asZ3IVdoNv3wti3YqXKY4GV
          volumeMounts:
            - name: staticweb
              mountPath: /app/etc
              subPath: uniauth/etc
            - name: staticweb
              mountPath: /app/static
              subPath: uniauth/static
      imagePullSecrets:
        - name: registry-cred
      volumes:
        - name: staticweb
          persistentVolumeClaim:
            claimName: staticweb-data
