apiVersion: v1
kind: Service
metadata:
  name: hl-metrics-api
spec:
  ports:
    - port: 8091
      targetPort: 8091
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: hl-metrics-api
subsets:
  - addresses:
      - ip: 192.168.99.108
    ports:
      - port: 8091
