apiVersion: batch/v1
kind: CronJob
metadata:
  name: hourly-ping
  namespace: default
spec:
  schedule: "0 * * * *"   # every hour at minute 0
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: ping
            image: busybox:1.36
            args:
              - /bin/sh
              - -c
              - |
                echo "Ping started at $(date)"
                ping -c 4 8.8.8.8
                echo "Ping finished at $(date)"

