apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv
  namespace: n8n
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rpi-nfs
  nfs:
    path: /srv/nfs/n8n
    server: 192.168.99.108
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
  namespace: n8n
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: rpi-nfs
