apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: disk-reporter
  namespace: default
spec:
  selector:
    matchLabels:
      app: disk-reporter
  template:
    metadata:
      labels:
        app: disk-reporter
    spec:
      hostPID: true                  # optional, if you need host info
      restartPolicy: Always
      containers:
      - name: disk-reporter
        image: bitnami/minideb:latest  # lightweight Debian with bash
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        command:
          - /bin/bash
          - -c
          - |
            apt-get update && apt-get install -y curl jq
            while true; do
              body=$(df -B1 / | tail -1 | awk '{printf "{ \"filesystem\": \"%s\", \"size\": %s, \"used\": %s, \"available\": %s, \"usage\": \"%s\", \"mountpoint\": \"%s\" }", $1, $2, $3, $4, $5, $6}' | jq --arg hostname "$HOSTNAME" '.hostname = $hostname')
              curl -X POST -H "Content-Type: application/json" -d "$body" http://192.168.99.108:8091/ping/disk
              sleep 3600  # 1 hour
            done

