apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rustfs
  namespace: s3
spec:
  serviceName: "rustfs"
  replicas: 1
  selector:
    matchLabels:
      app: rustfs
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      containers:
        - name: rustfs
          image: rustfs/rustfs:1.0.0-alpha.94
          securityContext:
            runAsUser: 0
          command: ["/bin/sh", "-c"]
          args:
            - >
              rustfs
              --console-enable
              --address "$RUSTFS_ADDRESS"
              --server-domains "$RUSTFS_SERVER_DOMAINS"
              --access-key "$RUSTFS_ACCESS_KEY"
              --secret-key "$RUSTFS_SECRET_KEY"
              /data
          envFrom:
            - secretRef:
                name: rustfs-creds
          volumeMounts:
            - name: rustfs-data
              mountPath: /data
      volumes:
        - name: rustfs-data
          persistentVolumeClaim:
            claimName: rustfs-data
