apiVersion: v1
kind: Service
metadata:
  name: rustfs
  namespace: s3
spec:
  type: ClusterIP
  selector:
    app: rustfs
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
