apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.99.108
  share: /srv/nfs
mountOptions:
  - nfsvers=4.2
  - hard
  - timeo=600
  - retrans=2
  - sync
  - noac
reclaimPolicy: Retain
volumeBindingMode: Immediate
