apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 10Gi
