apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: s3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 15Gi
