apiVersion: v1
kind: Service
metadata:
  name: n8n
spec:
  ports:
    - port: 5678
      targetPort: 5678
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: n8n
subsets:
  - addresses:
      - ip: 10.43.153.24
    ports:
      - port: 5678
