apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-web
  template:
    metadata:
      labels:
        app: personal-web
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: staticweb
              mountPath: /usr/share/nginx/html
              subPath: myweb
      volumes:
        - name: staticweb
          persistentVolumeClaim:
            claimName: staticweb-data
