apiVersion: apps/v1
kind: Deployment
metadata:
  name: services-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: services-web
  template:
    metadata:
      labels:
        app: services-web
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: staticweb
              mountPath: /usr/share/nginx/html
              subPath: mysrv
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: staticweb
          persistentVolumeClaim:
            claimName: staticweb-data
        - name: nginx-config
          configMap:
            name: nginx-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      root /usr/share/nginx/html;
      location / {
        try_files $uri $uri/ /index.html;
      }
    }
